const carParts = [
  "Engine",
  "Transmission",
  "Fuel Tank",
  "Carburetor",
  "Air Filter",
  "Oil Filter",
  "Fuel Pump",
  "Battery",
  "Spark Plug",
  "Exhaust System",
  "Muffler",
  "Clutch",
  "Gearbox",
  "Chain",
  "Sprocket",
  "Radiator",
  "Brake Pads",
  "Brake Discs",
  "Brake Caliper",
  "Brake Lever",
  "Brake Master Cylinder",
  "Brake Line",
  "Brake Fluid",
  // "Suspension Fork",
  // "Shock Absorber",
  // "Swingarm",
  // "Frame",
  // "Handlebar",
  // "Grips",
  // "Throttle",
  // "Clutch Lever",
  // "Foot Pegs",
  // "Kickstand",
  // "Side Stand",
  // "Center Stand",
  // "Wheels",
  // "Tires",
  // "Inner Tube",
  // "Wheel Bearings",
  // "Axle",
  // "Fender",
  // "Headlight",
  // "Tail Light",
  // "Turn Signal",
  // "Horn",
  // "Speedometer",
  // "Tachometer",
  // "Odometer",
  // "Fuel Gauge",
  // "Seat",
  // "Seat Cover",
  // "Seat Foam",
  // "Windshield",
  // "Mirrors",
  // "Fuel Cap",
  // "Gas Tank",
  // "Gaskets",
  // "Pistons",
  // "Cylinder Head",
  // "Crankshaft",
  // "Camshaft",
  // "Valves",
  // "Connecting Rod",
  // "Starter Motor",
  // "Ignition Coil",
  // "ECU (Engine Control Unit)",
  // "CDI (Capacitor Discharge Ignition)",
  // "Rectifier",
  // "Regulator",
  // "Stator",
  // "Rotor",
  // "Flywheel",
  // "Drive Belt",
  // "Gear Indicator",
  // "Kick Start",
  // "Radiator Fan",
  // "Coolant",
  // "Thermostat",
  // "Water Pump",
  // "Chain Guard",
  // "License Plate Holder",
  // "Tool Kit",
  // "First Aid Kit",
  // "Emergency Flares",
  // "Fire Extinguisher",
  // "Jumper Cables",
  // "Tire Inflator",
  // "Tire Pressure Gauge",
  // "Snow Chains",
  // "Bike Cover",
  // "Cleaning Supplies",
  // "Wax",
  // "Polish",
  // "Detailing Brush",
  // "Microfiber Cloth",
  // "Vacuum Cleaner",
  // "Air Freshener",
  // "Sun Shade",
  // "Dash Cam",
  // "OBD2 Scanner",
  // "Fuel Additives",
  // "Handlebar Mount",
  // "Phone Mount",
  // "USB Charger",
  // "GPS System",
  // "Audio System",
  // "Speakers",
  // "Amplifier",
  // "Subwoofer",
  // "Bluetooth Helmet",
  // "Riding Gear",
  // "Helmet",
  // "Gloves",
  // "Jacket",
  // "Pants",
  // "Boots",
  // "Body Armor",
  // "Rain Gear",
  // "Riding Suit",
  // "Knee Guards",
  // "Elbow Guards",
  // "Back Protector",
  // "Riding Goggles",
  // "Visor",
  // "Helmet Liner",
  // "Helmet Lock",
  // "Gear Shift Lever",
  // "Brake Pedal",
  // "Kickstand Spring",
  // "Helmet Holder",
  // "Rearview Camera",
  // "Parking Sensors",
  // "Anti-theft Alarm",
  // "Cover Lock",
  // "Chain Lock",
  // "Disc Lock",
  // "GPS Tracker",
  // "Cargo Rack",
  // "Saddle Bags",
  // "Top Box",
  // "Tank Bag",
  // "Tail Bag",
  // "Panniers",
  // "Helmet Bag",
  // "Cargo Net",
  // "Straps",
  // "Bungee Cord",
  // "Luggage Hook",
  // "Trailer Hitch",
  // "Trailer",
  // "Tow Strap"
];

export default carParts;
